services:
  postgres:
    image: postgres:16-alpine
    container_name: mustang-db
    environment:
      POSTGRES_USER: mustang
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mustang_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
